<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>EasyEject.UI</RootNamespace>
    <AssemblyName>EasyEject</AssemblyName>
    <LangVersion>preview</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\..\assets\icons\EasyEject.ico</ApplicationIcon>
    <Platforms>x64;ARM64</Platforms>
    <Platform Condition="'$(Platform)' == ''">x64</Platform>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == ''">win-x64</RuntimeIdentifier>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
    <SelfContained Condition="'$(Configuration)'=='Release'">true</SelfContained>
    <PublishSingleFile Condition="'$(Configuration)'=='Release'">true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.18" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.8249" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260710003" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasyEject.Core\EasyEject.Core.csproj" />
    <ProjectReference Include="..\EasyEject.Models\EasyEject.Models.csproj" />
    <ProjectReference Include="..\EasyEject.Services\EasyEject.Services.csproj" />
  </ItemGroup>

</Project>
