<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Version>1.0.0</Version>
    <Authors>EasyEject</Authors>
    <Product>EasyEject</Product>
    <Company>EasyEject</Company>
    <Copyright>Copyright (c) 2026 EasyEject</Copyright>
    <RepositoryUrl>https://github.com/easyeject/easyeject</RepositoryUrl>
  </PropertyGroup>
</Project>
