<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>EasyEject.Win32</RootNamespace>
    <AssemblyName>EasyEject.Win32</AssemblyName>
    <Platforms>x64;ARM64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasyEject.Models\EasyEject.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.10" />
  </ItemGroup>

</Project>
